In [21]:
import numpy as np 

# a=np.arange(15)
a=[1,3,4,5,6,7]
print(a)

[1, 3, 4, 5, 6, 7]


In [10]:
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
np.size(a)

15

In [25]:
b = [1,2,2,2,9,6]
# print(b)
np.add(a,b)

array([ 2,  5,  6,  7, 15, 13])

In [26]:
z = np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


In [29]:
z= np.ones(6)
print(z)

[1. 1. 1. 1. 1. 1.]


In [30]:
z.reshape(2,3)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
z = np.empty(3)
print(z)

[4.24399158e-314 4.24399158e-314 1.27319748e-313]


In [36]:
z = np.random.random((2,3))
print(z)


[[0.89675134 0.03651692 0.11851357]
 [0.06768943 0.27320102 0.70758904]]
